---
training_file : "../bach_data_minor.txt"
markov_order : 7
constraints : |
  E-3,C3,C3:G3,1
  __,__,__:__,2
  F3,D3,__:__,3
  __,__,__:__,4
  G3,E-3,E-2:C4,1
  __,__,__:__,2
  __,D3,__:__,3
  __,__,__:__,4
  G3,C3,G2:D4,1
  __,__,__:__,2
  __,B2,__:__,3
  __,__,__:__,4
  G3,C3,C2:E-4,1
  __,__,__:__,2
  A3,__,__:__,3
  __,__,__:__,4
  B3,F2,D2:D4,1
  __,__,__:__,2
  __,__,__:__,3
  __,__,__:__,4
  NC*32
  F3,D3,B2:G3,1
  __,__,__:__,2
  E3,C3,B-2:__,3
  __,__,__:__,4
  F3,C3,A2:C4,1
  __,__,__:__,2
  F#3,D3,A-2:__,3
  __,__,__:__,4
  G3,E-3,G2:C4,1
  __,__,__:__,2
  A3,D3,F#2:D4,3
  __,__,__:__,4
  G3,__,G2:B3,1
  __,__,__:__,2
  __,E-3,__:__,3
  __,F3,__:__,4
  G3,E-3,C2:C4,1
  __,__,__:__,2
  __,__,__:__,3
  __,__,__:__,4
  __,__,__:__,1
  __,__,__:__,2
  __,__,__:__,3
  __,__,__:__,4
  __,__,__:__,1
  __,__,__:__,2
  __,__,__:__,3
  __,__,__:__,4
